# Generated by Django 6.0.7 on 2026-07-25 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeuser',
            name='dob',
            field=models.DateTimeField(blank=True, max_length=10, null=True),
        ),
    ]
