# Generated by Django 6.0.7 on 2026-07-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_alter_customeuser_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customeuser',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customeuser',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
