# Generated by Django 6.0.3 on 2026-07-26 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_customeuser_gender_alter_customeuser_dob_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ELVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='ELvideo/')),
                ('alt', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
