# Generated by Django 6.0.3 on 2026-07-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_elvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('about_course', models.TextField()),
                ('course_image', models.ImageField(blank=True, null=True, upload_to='feature_course/')),
                ('starting_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.CharField(help_text="e.g., '3 Months', '30 Hours'", max_length=100)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
