# Generated by Django 6.0.3 on 2026-07-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter price in USD. Leave blank for free courses.', max_digits=8, null=True),
        ),
    ]
