# Generated by Django 6.0.3 on 2026-07-29 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_courses_discount_price_courses_instructor_enrollment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g., 'Week 1: Introduction'", max_length=200)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('meeting_link', models.URLField(blank=True, help_text='Link to the live class (e.g., Zoom, Google Meet)', null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_schedules', to='learning.courses')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
