# Generated by Django 6.0.3 on 2026-07-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_classschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='description',
            field=models.TextField(blank=True, help_text='A brief description of what will be covered in the class.', null=True),
        ),
    ]
