# Generated by Django 6.0.3 on 2026-08-01 12:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0009_classschedule_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classschedule',
            options={'ordering': ['start_date', 'start_time_of_day']},
        ),
        migrations.RemoveField(
            model_name='classschedule',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='classschedule',
            name='start_time',
        ),
        migrations.AddField(
            model_name='classschedule',
            name='end_date',
            field=models.DateField(default=1, help_text='The last date this class will occur.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classschedule',
            name='end_time_of_day',
            field=models.TimeField(default=1, help_text='The time the class ends each day (e.g., 11:00 AM)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classschedule',
            name='start_date',
            field=models.DateField(default=datetime.time(10, 0), help_text='The first date this class will occur.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classschedule',
            name='start_time_of_day',
            field=models.TimeField(default=datetime.time(10, 0), help_text='The time the class starts each day (e.g., 10:00 AM)'),
            preserve_default=False,
        ),
    ]
