# Generated by Django 6.0.7 on 2026-08-02 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0010_alter_classschedule_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordedClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('video', models.FileField(upload_to='recorded_classes/')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorded_classes', to='learning.courses')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
