# Generated by Django 6.0.3 on 2026-08-02 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0011_recordedclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordedclass',
            name='course_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original course fee for this recorded class.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='recordedclass',
            name='discount_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discounted fee for this recorded class, if applicable.', max_digits=8, null=True),
        ),
    ]
