# Generated by Django 6.0.3 on 2026-08-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0012_recordedclass_course_fee_recordedclass_discount_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordedclass',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Thumbnail image shown to preview users before enrollment.', null=True, upload_to='recorded_thumbnails/'),
        ),
    ]
